# Generated by Django 3.2.16 on 2023-07-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_auto_20230708_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(),
        ),
    ]
